### ISSUE TITLE
ParseFile must be saved before being set on a ParseObject

### ISSUE THREAD

**Issue by lucrus73** [thiagolocatelli/parse4j#17]
I use the following code with parse4j 1.3 in a wicket web application:

<pre>
        ParseQuery<Event> pq = ParseQuery.getQuery(Event.class);
        pq.skip((int)first);
        pq.limit((int)count);
        return pq.find().iterator();
</pre>

The find() call raises an IllegalArgumentException: ParseFile must be saved before being set on a ParseObject. However I'm not saving any object, I'm only fetching. Here is my Event class:

<pre>
@ParseClassName("Event")
public class Event extends ParseObject
{

  public String getEventLinkRegistration()
  {
    return getString("eventLinkRegistration");
  }

  public void setEventLinkRegistration(String eventLinkRegistration)
  {
    put("eventLinkRegistration", eventLinkRegistration);
  }

  public String getEventContactName()
  {
    return getString("eventContactName");
  }

  public void setEventContactName(String eventContactName)
  {
    put("eventContactName", eventContactName);
  }

  public String getEventContactMail()
  {
    return getString("eventContactMail");
  }

  public void setEventContactMail(String eventContactMail)
  {
    put("eventContactMail", eventContactMail);
  }

  public String getEventContactPhone()
  {
    return getString("eventContactPhone");
  }

  public void setEventContactPhone(String eventContactPhone)
  {
    put("eventContactPhone", eventContactPhone);
  }

  public String getEventAddress()
  {
    return getString("eventAddress");
  }

  public void setEventAddress(String eventAddress)
  {
    put ("eventAddress", eventAddress);
  }

  public String getEventCity()
  {
    return getString("eventCity");
  }

  public void setEventCity(String eventCity)
  {
    put("eventCity", eventCity);
  }

  public ParseRelation<Country> getEventCountry()
  {
    return getRelation("eventCountry");
  }

  public void setEventCountry(ParseRelation<Country> eventCountry)
  {
    put("eventCountry", eventCountry);
  }

  public String getEventTitle()
  {
    return getString("eventTitle");
  }

  public void setEventTitle(String eventTitle)
  {
    put("eventTitle", eventTitle);
  }

  public String getEventText()
  {
    return getString("eventText");
  }

  public void setEventText(String eventText)
  {
    put("eventText", eventText);
  }

  public Date getEventDate()
  {
    return getDate("eventDate");
  }

  public void setEventDate(Date eventDate)
  {
    put("eventDate", eventDate);
  }

  public ParseFile getEventImg()
  {
    return getParseFile("eventImg");
  }

  public void setEventImg(ParseFile eventImg)
  {
    put("eventImg", eventImg);
  }

  public ParseGeoPoint getEventPosition()
  {
    return getParseGeoPoint("eventPosition");
  }

  public void setEventPosition(ParseGeoPoint eventPosition)
  {
    put("eventPosition", eventPosition);
  }

}
</pre>

Here is the relevant part of the stack trace:

Caused by: java.lang.IllegalArgumentException: ParseFile must be saved before being set on a ParseObject.
	at org.parse4j.ParseObject.put(ParseObject.java:359)
	at org.parse4j.ParseObject.setData(ParseObject.java:725)
	at org.parse4j.ParseQuery.find(ParseQuery.java:499)

**Comment by Fjnova** [comment]
hi guys,
Is this issue fixed in ver 1.3 ?

I'm still get this error when I got data

**Comment by lucrus73** [comment]
I'm not sure, but I suspect 1.3 will always have the issue, because I reported the bug against 1.3 in the first place... maybe my patch will be include in a future release, maybe not, but 1.3 was released before I reported the bug.

**Comment by Gsx1992** [comment]
Can you upload the latest version to maven repository? Thanks

**Comment by thiagolocatelli** [comment]
I will manage to get the new version out there as soon as I can! Thank you

On Mon, Mar 2, 2015 at 9:19 AM, Gareth Lacey <notifications@github.com>
wrote:

> Can you upload the latest version to maven repository? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thiagolocatelli/parse4j/issues/17#issuecomment-76718692>
> .
>



-- 
"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')

**Comment by Gsx1992** [comment]
I see the readme has been updated saying that v1.4 is available but it doesn't appear to be working in maven.

**Comment by thiagolocatelli** [comment]
What kinda of error are you getting?

On Mon, Mar 2, 2015 at 3:16 PM, Gareth Lacey <notifications@github.com>
wrote:

> I see the readme has been updated saying that v1.4 is available but it
> doesn't appear to be working in maven.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thiagolocatelli/parse4j/issues/17#issuecomment-76806829>
> .
>



-- 
"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')

**Comment by Gsx1992** [comment]
Missing artifact com.github.thiagolocatelli:parse4j:jar:1.4. 1.3 works fine though.

**Comment by thiagolocatelli** [comment]
Thats interesting, I just tested it here and it is working, let me retry
after deleting my .m2 folder

On Mon, Mar 2, 2015 at 3:28 PM, Gareth Lacey <notifications@github.com>
wrote:

> Missing artifact com.github.thiagolocatelli:parse4j:jar:1.4. 1.3 works
> fine though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thiagolocatelli/parse4j/issues/17#issuecomment-76810604>
> .
>



-- 
"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')

**Comment by Gsx1992** [comment]
It's not on here either: http://mvnrepository.com/artifact/com.github.thiagolocatelli/parse4j

**Comment by thiagolocatelli** [comment]
its available here:

http://search.maven.org/#artifactdetails%7Ccom.github.thiagolocatelli%7Cparse4j%7C1.4%7Cjar

I have just removed my .m2 folder and forced the project to download the
jar again and it worked fine for me

On Mon, Mar 2, 2015 at 3:30 PM, Gareth Lacey <notifications@github.com>
wrote:

> It's not on here either:
> http://mvnrepository.com/artifact/com.github.thiagolocatelli/parse4j
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thiagolocatelli/parse4j/issues/17#issuecomment-76811570>
> .
>



-- 
"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')

**Comment by Gsx1992** [comment]
I have managed to fix it. Thanks for the help!

**Comment by thiagolocatelli** [comment]
No problem

On Mon, Mar 2, 2015 at 3:37 PM, Gareth Lacey <notifications@github.com>
wrote:

> I have managed to fix it. Thanks for the help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thiagolocatelli/parse4j/issues/17#issuecomment-76813993>
> .
>



-- 
"thiago:locatelli$gmail:com".replace(':','.').replace('$','@')
