### ISSUE TITLE
ParseObject saveAll Method

### ISSUE THREAD

**Issue by ucarseyhan** [thiagolocatelli/parse4j#31]
Dear All,
Is there any saveAll method in parse4j where we give list of parse object and all of them are saved in one query?

Regards.

**Comment by nickolayrusev** [comment]
Hi,
I implemented batch functionality and sent pull request. After the maintainer of this repo approve my pull request it will be available to save multiple objects with one call.

**Comment by ucarseyhan** [comment]
Dear nickolayrusev;

Thanks for information. Hope your pull request approved soon.

Regards.
