### ISSUE TITLE
Add Parse.initializeAsRoot(APP_ID, MASTER_API_KEY, PARSE_SERVER_URL)

### ISSUE THREAD

**Issue by noobs2ninjas** [thiagolocatelli/parse4j#76]
I don't see the ability to initialize as root through a self-hosted parse server. Being that we are so close to the hosted service shutting down, there is really no reason not to get this in there.

**Comment by tanzeelrana** [comment]
is this feature implemented ?

**Comment by SeloSlav** [comment]
@tanzeelrana Some users have got it working. I'm still trying to figure it out but no success so far. I asked a few question on SO at these links:

- http://stackoverflow.com/questions/43049967/conflicts-when-overriding-maven-dependency-with-local-changes
- http://stackoverflow.com/questions/43063719/parse4j-error-org-parse4j-parseobject-request-failed-exception-in-thread-m

**Comment by SeloSlav** [comment]
I haven't tried initializing as root but a hosted Parse-Server connection is now possible. See my answer: http://stackoverflow.com/questions/43110992/how-can-i-connect-to-a-hosted-parse-server-over-parse4j

**Comment by noobs2ninjas** [comment]
I actually went back and implemented it myself and just built out the jar and set it up as a local maven repository to get it compiled. Im actually trying to get in contact with the owner. I talked to the company I work for and a few fellow engineers and they are all interested in taking this over or  setting and hosting a public maven updates ourselves if the owner of parse4j doesn't have time to maintain it. Tried to hit him up on twitter and got no response.

**Comment by SeloSlav** [comment]
@noobs2ninjas  I'd also be interested in contributing. Seems like the original owner is inactive here. This could be really helpful, especially for Java-based web projects using Spring, Thymeleaf, etc. I had managed to get authentication working for a single user on the server but haven't got to differentiating sessions for multiple users, among other things. I've also been experimenting a lot with rendering ParseObjects via Thymeleaf. Good luck and do let me know if you get a team going to work on this!

**Comment by thiagolocatelli** [comment]
Sorry for not being able to reply, you guys can go ahead and fork and keep maintaining the project. Work has been taking a lot of my time and I Cant keep up with my OS projects.
