### ISSUE TITLE
To all who use this!

### ISSUE THREAD

**Issue by noobs2ninjas** [thiagolocatelli/parse4j#82]
So, Ive been trying to get in touch with @thiagolocatelli and I cant seem to get him to respond. A few guys I work with have been talking about forking this and doing some major upgrades and improvements and hosting a public maven update on our own. 

On our side we are already doing improvements to things like initializing as root with a self-hosted Parse server. We have also been working on batch functionality.

Anyway, before we did any major work and took all this upon ourselves I first wanted to give @thiagolocatelli a chance to possibly respond here and tell us that he is still wanting to keep working on this. I also make sure that this is something that the parse4j users would like as well.

**Comment by thiagolocatelli** [comment]
I have not been able to keep up with my emails. I havent been able to give too much attention to this project so you are welcome to fork it and do all the improvements necessary and host your own maven update.
